export type Permission =
  | 'create:articles'
  | 'update:articles'
  | 'delete:articles'
  | 'view:users'
  | 'create:users'
  | 'update:users'
  | 'delete:users'
  | 'view:roles'
  | 'create:roles'
  | 'update:roles'
  | 'delete:roles'
